# SPDX-License-Identifier: GPL-2.0
# Makefile for Intel Timed IO (TIO) PPS selftests

TEST_PROGS := test_pps_gen_tio.sh test_pps_platform_tio.sh test_pps_client_tio.sh
TEST_FILES := pps_tio_common.sh

include ../../../../../lib.mk
